# Generated by Django 5.2.10 on 2026-01-31 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.booking'),
        ),
    ]
