# Generated by Django 5.2.10 on 2026-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_structured_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='change_rooms',
            field=models.BooleanField(default=False, verbose_name='Change rooms'),
        ),
        migrations.AddField(
            model_name='facility',
            name='food_and_beverage',
            field=models.BooleanField(default=False, verbose_name='Food & beverage'),
        ),
        migrations.AddField(
            model_name='facility',
            name='gym_weight_room',
            field=models.BooleanField(default=False, verbose_name='Gym / weight room'),
        ),
        migrations.AddField(
            model_name='facility',
            name='handicap_accessible',
            field=models.BooleanField(default=False, verbose_name='Handicap accessible'),
        ),
        migrations.AddField(
            model_name='facility',
            name='licensed',
            field=models.BooleanField(default=False, verbose_name='Licensed (alcohol)'),
        ),
        migrations.AddField(
            model_name='facility',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='facility',
            name='pro_shop',
            field=models.BooleanField(default=False, verbose_name='Pro shop'),
        ),
        migrations.AddField(
            model_name='facility',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='Wi‑Fi'),
        ),
    ]
